kind: Deployment
apiVersion: apps/v1
metadata:
  name: guide-spring-boot
spec:
  selector:
    matchLabels:
      app: guide-spring-boot
  replicas: 1
  template:
    metadata:
      labels:
        app: guide-spring-boot
        version: v1
    spec:
      containers:
      - name: authors
        image: quay.io/marcf5/guide-spring-boot
        ports:
        - containerPort: 9080
        livenessProbe:
          exec:
            command: ["sh", "-c", "curl -s http://localhost:9080/"]
          initialDelaySeconds: 20
        readinessProbe:
          exec:
            command: ["sh", "-c", "curl -s http://localhost:9080/hello"]
          initialDelaySeconds: 40
      restartPolicy: Always
      imagePullSecrets:
        - name: staging-secret
---
